In [1]:
import numpy as np

In [2]:
# here are some height data in inches
height = [72,68,69,68,64,72,72]

In [3]:
%%timeit

# Convert these height data from inches to meters (1 inch = 0.0254 m)
height_meter = np.multiply(height,0.0254)
height_meter

2.22 µs ± 59.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
%%timeit

for i in range(len(height)):
    height[i] *= 0.0254


669 ns ± 12.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
# another numpy solution
height = [72,68,69,68,64,72,72]

np_height = np.array(height)
print(height)
np_height_m = np_height*0.025
print(np_height_m)

[72, 68, 69, 68, 64, 72, 72]
[1.8   1.7   1.725 1.7   1.6   1.8   1.8  ]


In [6]:
mylist1 = [2,4,6]
mylist2 = [1,3,5]
print(mylist1 + mylist2)

[2, 4, 6, 1, 3, 5]


In [7]:
np_mylist1 = np.array(mylist1)
np_mylist2 = np.array(mylist2)
print(np_mylist1 + np_mylist2)

[ 3  7 11]


In [8]:
numbers = [10,15,20,35]
numbers2 = [10.0,15.1,19.5]

In [9]:
x = np.array(numbers, dtype='float') # possible to set dtype at the beginning
y = np.array(numbers2)
print(x)
print(y)

[10. 15. 20. 35.]
[10.  15.1 19.5]


In [10]:
x.dtype

dtype('float64')

In [11]:
x

array([10., 15., 20., 35.])

In [12]:
x[0] # first element

10.0

In [13]:
x[0:2] # first two elements

array([10., 15.])

In [14]:
x[2:]  # last two elements

array([20., 35.])

In [15]:
x[::-1] # reverses the array

array([35., 20., 15., 10.])

In [16]:
np.arange(1,8,1)

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
np.arange(1,8) # default step is 1

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [19]:
np.arange(1,8,5)

array([1, 6])

In [20]:
np.arange(-6,3) # works with negative numbers

array([-6, -5, -4, -3, -2, -1,  0,  1,  2])

In [21]:
np.arange(2,10.1,2) # this includes 10

array([ 2.,  4.,  6.,  8., 10.])

In [22]:
np.arange(2,10,2) # does not include 10

array([2, 4, 6, 8])

In [23]:
np.arange(5,1,-1) # reverse order

array([5, 4, 3, 2])

In [24]:
print(x)

[10. 15. 20. 35.]


In [25]:
# slice x such that you get returned entries>=20
x[x>=20]

array([20., 35.])

In [26]:
# multiple conditions, and
# return elements in x that are <12 and > 25
x[(x>25) & (x<12)]

array([], dtype=float64)

In [27]:
# multiple conditions, or
# return elements in x that are <12 or > 25
x[(x>25) | (x<12)]

array([10., 35.])

In [28]:
# return elements equal to 20
x[x==20]

array([20.])

In [29]:
# return all elements except 20
x[~(x==20)]

array([10., 15., 35.])

In [30]:
# 2d arrays
# here are some height data in inches
height = [72,68,69,68,64,72,72]
# here are some weight data in lbs
weight = [200,165,160,135,120,162,190]

# create a 2d numpy array
metrics = np.array([height,weight])
print(metrics)

[[ 72  68  69  68  64  72  72]
 [200 165 160 135 120 162 190]]


In [31]:
metrics.shape # shape of matrix

(2, 7)

In [32]:
metrics.size # size of the matrix

14

In [33]:
metrics.ndim # dimensions of the matrix

2

In [34]:
metrics[1,2] # access 160: row position 1, col position 2

160

In [35]:
metrics[1][2] # same number returned

160

In [36]:
metrics[1,0:3] # return 200 165 160: row position 1, col position 0:3

array([200, 165, 160])

In [49]:
# reshape() function
# create a vector of numbers from 1 through 9, step=1
x = np.arange(1,10)
x.reshape(3,3) # convert x such that x now has 3 rows and 3 colprint(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# resize() overwrites the object
x = np.arange(1,10)
x.resize(3,3) # convert x such that x now has 3 rows and 3 cols
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
data = np.array([[72,200],[68,165],[69,160],[68,138],[64,120],[72,162]])
data

array([[ 72, 200],
       [ 68, 165],
       [ 69, 160],
       [ 68, 138],
       [ 64, 120],
       [ 72, 162]])

In [55]:
# 1 inch = 0.0254 meter
# 1 lbs = 0.453 kg
# convert the inch and lbs data to meters and kgs:
data * np.array([.0254,.453])
# alternative:
np.multiply(data, [.0254,.453])

array([[ 1.8288, 90.6   ],
       [ 1.7272, 74.745 ],
       [ 1.7526, 72.48  ],
       [ 1.7272, 62.514 ],
       [ 1.6256, 54.36  ],
       [ 1.8288, 73.386 ]])

In [61]:
#3d array
data = np.arange(0,36).reshape(3,4,3) # first number is matrix num, second is 
#num of rows in each matrix, third is num of cols in each matrix
data

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [63]:
# access "27":
data[2,1,0]

27

In [64]:
# access the second col of matrix 3
data[2,:,1] # ":" chooses all rows

array([25, 28, 31, 34])

In [67]:
a = np.ones((2,5,1,8,4))
a

array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
    

In [65]:
b=np.ones((3,1,4))
b

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])