In [7]:
import numpy as np

In [12]:
# here are some height data in inches
height = [72,68,69,68,64,72,72]

In [13]:
%%timeit

# Convert these height data from inches to meters (1 inch = 0.0254 m)
height_meter = np.multiply(height,0.0254)
height_meter

2.2 µs ± 66.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%%timeit

for i in range(len(height)):
    height[i] *= 0.0254


675 ns ± 5.83 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [17]:
# another numpy solution
height = [72,68,69,68,64,72,72]

np_height = np.array(height)
print(height)
np_height_m = np_height*0.025
print(np_height_m)

[72, 68, 69, 68, 64, 72, 72]
[1.8   1.7   1.725 1.7   1.6   1.8   1.8  ]


In [18]:
mylist1 = [2,4,6]
mylist2 = [1,3,5]
print(mylist1 + mylist2)

[2, 4, 6, 1, 3, 5]


In [19]:
np_mylist1 = np.array(mylist1)
np_mylist2 = np.array(mylist2)
print(np_mylist1 + np_mylist2)

[ 3  7 11]


In [21]:
numbers = [10,15,20,35]
numbers2 = [10.0,15.1,19.5]

In [27]:
x = np.array(numbers, dtype='float') # possible to set dtype at the beginning
y = np.array(numbers2)
print(x)
print(y)

[10. 15. 20. 35.]
[10.  15.1 19.5]


In [28]:
x.dtype

dtype('float64')

In [32]:
x

array([10., 15., 20., 35.])

In [35]:
x[0] # first element

10.0

In [33]:
x[0:2] # first two elements

array([10., 15.])

In [34]:
x[2:]  # last two elements

array([20., 35.])

In [36]:
x[::-1] # reverses the array

array([35., 20., 15., 10.])

In [37]:
np.arange(1,8,1)

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
np.arange(1,8) # default step is 1

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [40]:
np.arange(1,8,5)

array([1, 6])

In [41]:
np.arange(-6,3) # works with negative numbers

array([-6, -5, -4, -3, -2, -1,  0,  1,  2])

In [42]:
np.arange(2,10.1,2) # this includes 10

array([ 2.,  4.,  6.,  8., 10.])

In [43]:
np.arange(2,10,2) # does not include 10

array([2, 4, 6, 8])

In [44]:
np.arange(5,1,-1) # reverse order

array([5, 4, 3, 2])

In [45]:
print(x)

[10. 15. 20. 35.]


In [47]:
# slice x such that you get returned entries>=20
x[x>=20]

array([20., 35.])

In [49]:
# multiple conditions, and
# return elements in x that are <12 and > 25
x[(x>25) & (x<12)]

array([], dtype=float64)

In [51]:
# multiple conditions, or
# return elements in x that are <12 or > 25
x[(x>25) | (x<12)]

array([10., 35.])

In [54]:
# return elements equal to 20
x[x==20]

array([20.])

In [53]:
# return all elements except 20
x[~(x==20)]

array([10., 15., 35.])

In [60]:
# 2d arrays
# here are some height data in inches
height = [72,68,69,68,64,72,72]
# here are some weight data in lbs
weight = [200,165,160,135,120,162,190]

# create a 2d numpy array
metrics = np.array([height,weight])
print(metrics)

[[ 72  68  69  68  64  72  72]
 [200 165 160 135 120 162 190]]


In [62]:
metrics.shape # shape of matrix

(2, 7)

In [63]:
metrics.size # size of the matrix

14

In [64]:
metrics.ndim # dimensions of the matrix

2

In [65]:
metrics[1,2] # access 160: row position 1, col position 2

160

In [67]:
metrics[1][2] # same number returned

160

In [68]:
metrics[1,0:3] # return 200 165 160: row position 1, col position 0:3

array([200, 165, 160])

In [71]:
# reshape() function
# create a vector of numbers from 1 through 9, step=1
x = np.arange(1,10)
x.reshape(3,3) # convert x such that x now has 3 rows and 3 cols

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])